FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY Server ./Server
RUN dotnet restore Server/RaceGame.Api/RaceGame.Api.csproj
RUN dotnet publish Server/RaceGame.Api/RaceGame.Api.csproj -c Release -o /app/publish --no-restore
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/publish ./
EXPOSE 8080
ENTRYPOINT ["dotnet", "RaceGame.Api.dll"]
