FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY Server ./Server
RUN dotnet restore Server/RaceGame.Admin/RaceGame.Admin.csproj
RUN dotnet publish Server/RaceGame.Admin/RaceGame.Admin.csproj -c Release -o /app/publish --no-restore
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/publish ./
EXPOSE 8081
ENTRYPOINT ["dotnet", "RaceGame.Admin.dll"]
